name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create environment files from templates  
        run: |
          cp src/app/environment.prod.ts src/app/environment.ts

      - name: Replace Firebase config with secrets
        env:
          NG_APP_FIREBASE_API_KEY: ${{ secrets.NG_APP_FIREBASE_API_KEY }}
          NG_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.NG_APP_FIREBASE_AUTH_DOMAIN }}
          NG_APP_FIREBASE_DATABASE_URL: ${{ secrets.NG_APP_FIREBASE_DATABASE_URL }}
          NG_APP_FIREBASE_PROJECT_ID: ${{ secrets.NG_APP_FIREBASE_PROJECT_ID }}
          NG_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.NG_APP_FIREBASE_STORAGE_BUCKET }}
          NG_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NG_APP_FIREBASE_MESSAGING_SENDER_ID }}
          NG_APP_FIREBASE_APP_ID: ${{ secrets.NG_APP_FIREBASE_APP_ID }}
        run: |
          # Replace placeholders in both files
          sed -i "s/YOUR_FIREBASE_API_KEY/$NG_APP_FIREBASE_API_KEY/g" src/app/environment.ts
          sed -i "s/YOUR_FIREBASE_AUTH_DOMAIN/$NG_APP_FIREBASE_AUTH_DOMAIN/g" src/app/environment.ts
          sed -i "s|YOUR_FIREBASE_DATABASE_URL|$NG_APP_FIREBASE_DATABASE_URL|g" src/app/environment.ts
          sed -i "s/YOUR_FIREBASE_PROJECT_ID/$NG_APP_FIREBASE_PROJECT_ID/g" src/app/environment.ts
          sed -i "s/YOUR_FIREBASE_STORAGE_BUCKET/$NG_APP_FIREBASE_STORAGE_BUCKET/g" src/app/environment.ts
          sed -i "s/YOUR_FIREBASE_MESSAGING_SENDER_ID/$NG_APP_FIREBASE_MESSAGING_SENDER_ID/g" src/app/environment.ts
          sed -i "s/YOUR_FIREBASE_APP_ID/$NG_APP_FIREBASE_APP_ID/g" src/app/environment.ts
          
          # Also replace in prod file and set production: true
          sed -i "s/YOUR_FIREBASE_API_KEY/$NG_APP_FIREBASE_API_KEY/g" src/app/environment.prod.ts
          sed -i "s/YOUR_FIREBASE_AUTH_DOMAIN/$NG_APP_FIREBASE_AUTH_DOMAIN/g" src/app/environment.prod.ts
          sed -i "s|YOUR_FIREBASE_DATABASE_URL|$NG_APP_FIREBASE_DATABASE_URL|g" src/app/environment.prod.ts
          sed -i "s/YOUR_FIREBASE_PROJECT_ID/$NG_APP_FIREBASE_PROJECT_ID/g" src/app/environment.prod.ts
          sed -i "s/YOUR_FIREBASE_STORAGE_BUCKET/$NG_APP_FIREBASE_STORAGE_BUCKET/g" src/app/environment.prod.ts
          sed -i "s/YOUR_FIREBASE_MESSAGING_SENDER_ID/$NG_APP_FIREBASE_MESSAGING_SENDER_ID/g" src/app/environment.prod.ts
          sed -i "s/YOUR_FIREBASE_APP_ID/$NG_APP_FIREBASE_APP_ID/g" src/app/environment.prod.ts
          sed -i "s/production: false/production: true/g" src/app/environment.prod.ts

      - name: Build Angular app
        run: |
          npm run build -- --configuration=production --base-href="/cabbingov2/"
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/cabbingov2/browser